// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP01AppWeb.Models.Entreprise;

namespace TP01AppWeb.Migrations
{
    [DbContext(typeof(ContextEntreprise))]
    partial class ContextEntrepriseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TP01AppWeb.Models.Entreprise.Succursale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("CodePostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoCivic")
                        .HasColumnType("int");

                    b.Property<string>("NoTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Succursales");
                });

            modelBuilder.Entity("TP01AppWeb.Models.Entreprise.Voiture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<int>("Groupe")
                        .HasColumnType("int");

                    b.Property<int>("Millage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoVoiture")
                        .HasColumnType("int");

                    b.Property<int?>("SuccursaleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuccursaleId");

                    b.ToTable("Voitures");
                });

            modelBuilder.Entity("TP01AppWeb.Models.Entreprise.Voiture", b =>
                {
                    b.HasOne("TP01AppWeb.Models.Entreprise.Succursale", null)
                        .WithMany("Voiture")
                        .HasForeignKey("SuccursaleId");
                });

            modelBuilder.Entity("TP01AppWeb.Models.Entreprise.Succursale", b =>
                {
                    b.Navigation("Voiture");
                });
#pragma warning restore 612, 618
        }
    }
}
